apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
spec:
  containers:
    - image: busybox:latest
      name: pod
      command: ["ping"]
      args: ['-c','60','google.com']
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
