apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: new-ping-pod
  name: new-ping-pod
spec:
  containers:
  - command:
    - ping
    - -c
    - "60"
    - google.com
    image: busybox:latest
    name: new-ping-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
